"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type Agent={nome:string;funcao?:string;partidas:number;score:number;confianca:string;analise?:string;stats_reais:{win_rate:number;kd:number;adr:number;acs:number;kast:number}};
type MapRow={mapa:string;partidas:number;vitorias:number;derrotas:number;win_rate_real:number;score:number;melhor_agente_estimado:{agente:string|null;chance_estimada:number|null;confianca:string}};
type Insights={metadata:{jogador:string;gerado_em:string;quantidade_agentes:number;quantidade_mapas:number};agentes:{top_5:Agent[];ranking_completo:Agent[];criterio_top_5:{minimo_partidas:number}};mapas:{ranking:MapRow[]};resumo:{melhor_agente_geral:string;melhor_mapa:string;pior_mapa:string}};

const demo:Insights={metadata:{jogador:"elsewhere#999t",gerado_em:new Date().toISOString(),quantidade_agentes:13,quantidade_mapas:7},agentes:{criterio_top_5:{minimo_partidas:5},ranking_completo:[],top_5:[
 {nome:"Clove",funcao:"Controller",partidas:61,score:85.87,confianca:"alta",analise:"Maior consistência da amostra e impacto sólido por rodada.",stats_reais:{win_rate:42.6,kd:.87,adr:151.5,acs:227.7,kast:73.7}},
 {nome:"Jett",funcao:"Duelist",partidas:28,score:85.74,confianca:"alta",stats_reais:{win_rate:46.4,kd:.94,adr:146.9,acs:218.9,kast:70.2}},
 {nome:"Chamber",funcao:"Sentinel",partidas:13,score:68.64,confianca:"media",stats_reais:{win_rate:61.5,kd:.86,adr:125.6,acs:188.2,kast:67.9}},
 {nome:"Sova",funcao:"Initiator",partidas:13,score:56.92,confianca:"media",stats_reais:{win_rate:38.5,kd:.9,adr:140.2,acs:201.3,kast:71.2}},
 {nome:"Phoenix",funcao:"Duelist",partidas:7,score:34.68,confianca:"baixa",stats_reais:{win_rate:42.9,kd:.71,adr:122.7,acs:174.8,kast:60.7}}]},
 mapas:{ranking:[["Ascent",100,"Clove",48.08,20,11,9,55],["Summit",76.85,"Jett",77.69,20,12,8,60],["Haven",67.24,"Jett",65.74,23,14,9,60.9],["Sunset",58.81,"Clove",60.77,20,10,10,50],["Lotus",46.91,"Jett",48.6,18,8,10,44.4],["Breeze",33.23,"Sova",36.84,20,6,14,30],["Split",0,"Clove",20.45,18,3,15,15.8]].map(([mapa,score,agente,chance,partidas,vitorias,derrotas,wr])=>({mapa,score,partidas,vitorias,derrotas,win_rate_real:wr,melhor_agente_estimado:{agente,chance_estimada:chance,confianca:"media"}} as MapRow))},resumo:{melhor_agente_geral:"Clove",melhor_mapa:"Ascent",pior_mapa:"Split"}};
const pct=(v?:number|null)=>`${Number(v??0).toFixed(1)}%`;
const conf=(v:string)=>({alta:"Alta",media:"Média",baixa:"Baixa",muito_baixa:"Muito baixa"} as Record<string,string>)[v]??v;

export default function Home(){
 const [data,setData]=useState(demo),[tab,setTab]=useState("overview"),[updated,setUpdated]=useState<Date|null>(null),[source,setSource]=useState("Demonstração"),[pulse,setPulse]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch(`/tracker_insights.json?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;setData(await r.json());setUpdated(new Date());setSource("JSON conectado");setPulse(true);setTimeout(()=>setPulse(false),650)}catch{}},[]);
 useEffect(()=>{setUpdated(new Date());load();const id=setInterval(load,3000);return()=>clearInterval(id)},[load]);
 const agents=data.agentes.top_5??[],maps=data.mapas.ranking??[],best=agents[0];
 const total=useMemo(()=>maps.reduce((s,m)=>s+m.partidas,0),[maps]);
 return <main><div className="aurora one"/><div className="aurora two"/><div className="noise"/>
  <header><a className="brand"><i>E</i> ELSEWHERE <b>LAB</b></a><nav>{[["overview","Visão geral"],["agents","Agentes"],["maps","Mapas"]].map(([id,l])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{l}</button>)}</nav><div className={`live ${pulse?"pulse":""}`}><i/><span>{source}</span><small>{updated?updated.toLocaleTimeString("pt-BR"):"--:--:--"}</small></div></header>
  <section className="hero"><div><p className="eyebrow">VALORANT PERFORMANCE INTELLIGENCE</p><h1>Decisões melhores.<br/><span>Rounds mais inteligentes.</span></h1><p className="lede">Uma leitura estatística do seu jogo que reduz o ruído de amostras pequenas e revela onde sua performance realmente se sustenta.</p></div><div className="orb"><span>PLAYER SIGNAL</span><strong>{data.metadata.jogador?.split("#")[0]}</strong><small>#{data.metadata.jogador?.split("#")[1]} · COMPETITIVE</small><i/><b/></div></section>
  {tab==="overview"&&<><section className="metrics"><Metric icon="✦" label="Agente principal" value={data.resumo.melhor_agente_geral} note={`${best?.partidas??0} partidas analisadas`}/><Metric icon="⌁" label="Melhor mapa" value={data.resumo.melhor_mapa} note={`${maps[0]?.score?.toFixed(0)??0}/100 performance score`}/><Metric icon="◫" label="Amostra total" value={`${total}`} note={`${data.metadata.quantidade_mapas} mapas no recorte`}/><Metric icon="△" label="Zona de atenção" value={data.resumo.pior_mapa} note={`${pct(maps.at(-1)?.win_rate_real)} win rate`} danger/></section>
  <section className="main-grid"><article className="panel"><Head over="RANKING AJUSTADO" title="Top 5 agentes" note={`Mínimo ${data.agentes.criterio_top_5?.minimo_partidas??5} partidas`}/><div>{agents.map((a,i)=><AgentRow agent={a} index={i} key={a.nome}/>)}</div></article><article className="panel"><Head over="MAP POOL" title="Território de vantagem" note="Score conservador"/><div className="map-stack">{maps.slice(0,5).map((m,i)=><MapBar map={m} index={i} key={m.mapa}/>)}</div></article></section>
  <section className="insight"><div className="spark">✦</div><div><span>INSIGHT CENTRAL</span><h3>{best?.nome} é sua escolha de maior sustentação estatística.</h3><p>{best?.analise??"Volume e performance ajustada colocam esse agente no topo da análise."}</p></div><div className="ring" style={{"--score":`${best?.score??0}%`} as React.CSSProperties}><strong>{best?.score?.toFixed(0)}</strong><small>SCORE</small></div></section></>}
  {tab==="agents"&&<section className="panel full"><Head over="AGENT DEEP DIVE" title="Seu arsenal competitivo" note="Stats reais + confiança"/><div className="agent-cards">{agents.map((a,i)=><AgentCard agent={a} index={i} key={a.nome}/>)}</div></section>}
  {tab==="maps"&&<section className="panel full"><Head over="MAP INTELLIGENCE" title="Mapa por mapa" note="Melhor pick estimado"/><div className="map-grid">{maps.map((m,i)=><MapCard map={m} index={i} key={m.mapa}/>)}</div></section>}
  <footer><b>ELSEWHERE PERFORMANCE LAB</b><p>Atualização automática a cada 3 segundos · análise conservadora de amostra</p><button onClick={load}>Atualizar agora ↻</button></footer>
 </main>
}
function Metric({icon,label,value,note,danger}:{icon:string,label:string,value:string,note:string,danger?:boolean}){return <article className={`metric ${danger?"danger":""}`}><i>{icon}</i><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Head({over,title,note}:{over:string,title:string,note:string}){return <div className="head"><div><span>{over}</span><h2>{title}</h2></div><small>{note}</small></div>}
function AgentRow({agent:a,index:i}:{agent:Agent,index:number}){return <div className="agent-row"><b>0{i+1}</b><i>{a.nome[0]}</i><div><strong>{a.nome}</strong><small>{a.funcao}</small></div><span><i style={{width:`${a.score}%`}}/></span><div className="score"><strong>{a.score.toFixed(1)}</strong><small>{a.partidas} partidas</small></div></div>}
function MapBar({map:m,index:i}:{map:MapRow,index:number}){return <div className="map-bar"><small>0{i+1}</small><div><strong>{m.mapa}</strong><span>{m.melhor_agente_estimado.agente} · {pct(m.melhor_agente_estimado.chance_estimada)}</span></div><i><b style={{height:`${Math.max(m.score,4)}%`}}/></i><strong>{m.score.toFixed(0)}</strong></div>}
function AgentCard({agent:a,index:i}:{agent:Agent,index:number}){return <article className="agent-card"><div className="card-top"><span>#{i+1}</span><i>{conf(a.confianca)} confiança</i></div><div className="mono">{a.nome.slice(0,2).toUpperCase()}</div><h3>{a.nome}</h3><p>{a.funcao} · {a.partidas} partidas</p><div className="stats"><span><b>{pct(a.stats_reais.win_rate)}</b>WIN</span><span><b>{a.stats_reais.kd.toFixed(2)}</b>K/D</span><span><b>{a.stats_reais.acs.toFixed(0)}</b>ACS</span></div><div className="scoreline"><i style={{width:`${a.score}%`}}/></div><strong className="big">{a.score.toFixed(1)}</strong></article>}
function MapCard({map:m,index:i}:{map:MapRow,index:number}){return <article className="map-card"><b>0{i+1}</b><div><span>PERFORMANCE MAP</span><h3>{m.mapa}</h3><p>{m.vitorias}V · {m.derrotas}D · {m.partidas} partidas</p></div><div className="pick"><span>MELHOR PICK</span><strong>{m.melhor_agente_estimado.agente??"—"}</strong><small>{pct(m.melhor_agente_estimado.chance_estimada)} estimado</small></div><div className="wr"><strong>{pct(m.win_rate_real)}</strong><span>WIN RATE</span></div><i className="mapline" style={{width:`${m.score}%`}}/></article>}
